KWEBofficial/kubid-client

package-lock.json, package.json, src/App.tsx, src/api/auth/index.ts, src/api/index.ts, src/api/users/index.ts, src/components/common/CustomLayout.tsx, src/components/common/LinksInNav.tsx, src/components/passwordchange/GrayButton.tsx, src/components/signup/BlueButton.tsx, src/components/signup/LargeInput.tsx, src/components/signup/MatchingPasswordInput.tsx, src/main.tsx, src/models/user.ts, src/pages/PasswordChange/PasswordChangeLayout.tsx, src/pages/PasswordChange/index.tsx, src/pages/SignIn/SignInLayout.tsx, src/pages/SignUp/SignUpLayout.tsx, src/pages/SignUp/index.tsx, src/routes/index.tsx, src/styles/sizes.ts
비밀번호 변경하는 페이지 구현했습니다.
현재 비밀번호와 새로운 비밀번호를 넘겨준 다음에 현재 비밀번호 checking 후 새로운 비밀번호로 설정해주는 방향으로 API를 조금 변경해야 될 것 같습니다.
+ 회원가입, 로그인, 네비게이션바에서 사소한 변경사항들도 있습니다.
=> feat: Implement Password Change Page

src/api/product/index.ts, src/components/common/SearchSection.tsx, src/components/common/SearchSection/SearchInput.tsx, src/pages/mainpage.tsx, src/pages/searchpage.tsx, src/routes/index.tsx
https://github.com/KWEBofficial/kubid-client/assets/115782193/d1842fb3-7e60-426b-8d1c-503fedfc220f
검색 페이지를 구현했습니다.
- 한 페이지당 4개씩 나오게 했습니다 (추후 조정 가능)
- Enter 키 사용 가능
- 검색 결과 뜨고 입력 창에 자동으로 focus되게 했습니다. (영상에는 미반영)
=> Feature: 검색 페이지

src/components/mypage/ItemList/ItemListBody/ItemButton.tsx, src/components/mypage/PersonalInfo/personalImage.tsx, src/components/mypage/PersonalInformation.tsx
- 사용자 프로필 사진이 없을 경우 마이페이지 접속이 안 되는 버그를 해결했습니다.
=> Fix: 마이페이지 접속이 안 되는 버그 해결

src/api/user/index.ts, src/api/users/index.ts, src/components/mypage/PersonalInfo/personalImage.tsx, src/components/mypage/PersonalInfo/personalinfoBody.tsx, src/components/mypage/PersonalInformation.tsx, src/models/user.ts, src/pages/MyPage.tsx, src/routes/index.tsx
- 닉네임을 수정하는 기능을 구혔습니다.
- 프로필 사진을 수정하는 기능을 구혔습니다.
- 비밀번호 수정 페이지를 링킹 시켰습니다.
=> feat: 마이페이지 닉네임 프로필 사진 수정 구현

src/components/mypage/ItemList/ItemListBody/ItemButton.tsx, src/components/mypage/PersonalInfo/MyBoxBody.tsx
- npm run build 실행 시 뜨는 minor bug를 fix했습니다.
=> Fix: build error fix

src/components/common/SearchSection/SearchInput.tsx
=> fix: navigate instead of using href

src/components/common/ItemList.tsx, src/components/common/ItemList/ItemListBody.tsx, src/components/common/ItemList/ItemListBody/ItemButton.tsx, src/components/mypage/ItemList/ItemListBody/ItemButton.tsx, src/components/mypage/PersonalInfo/personalImage.tsx, src/models/product.ts, src/pages/MyPage.tsx
- MyPage item에서 학과명과 progressbar가 나타나게 구현했습니다.
- MyPage 에서 Item List 로 common component를 사용하게 리팩토링 했습니다.
=> mod : implement department name & progress bar on items in mypage + refactorized mypage

src/components/signup/PasswordInput.tsx, src/pages/SignIn/SignInLayout.tsx
=> hotfix : password

package-lock.json, package.json, src/components/ProductRegister/FormContainer.tsx, src/components/ProductRegister/Tags.tsx, src/components/common/ImageUploadButton.tsx, src/pages/ProductRegister/ProductRegister.tsx
- 상품 등록이 성공하면 성공 팝업창이 뜨도록 수정하였습니다 .
=> Feature: 상품 등록 후 팝업창 띄우기 

src/api/auth/index.ts, src/pages/SignUp/SignUpLayout.tsx
=> hotfix : sign-up

src/pages/SignUp/SignUpLayout.tsx
회원가입 페이지에서도 이메일 검증이 들어갑니다.
값이 없으면 버튼이 활성화가 안되고, 이메일이나 비밀번호 부분에서 값이 올바르지 않으면 버튼을 눌러도 회원가입이 진행이 안됩니다.
=> fix: Implement Form tag at sign-up page

src/pages/mainpage.tsx
- 전체 인기 상품과 겹치는 학과 인기 상품을 거르지 않고 그냥 보여주는 것으로 수정했습니다
=> fix: remove overlap filter in deptPopularProducts

src/components/common/SearchSection.tsx
- 메인 페이지에서 입력한 검색어와 학과 선택 정보가 검색 결과 페이지에 유지되도록 수정
=> fix: keep last search from mainpage

src/components/common/SearchSection/SearchInput.tsx, src/pages/searchpage.tsx
- 학과 선택을 바꿨을 때 검색 버튼이나 Enter를 누르지 않고도 바로 검색이 되게 수정
- 검색어가 없을 때는 검색하지 않음
=> fix: search if department changes

src/components/productdetail/ProductInfo.tsx
=> fix: Show upperbound when no bidder

src/pages/PasswordChange/PasswordChangeLayout.tsx, src/pages/SignIn/SignInLayout.tsx
패스워드 수정시 기존 패스워드와 일치하지 않으면 에러 메세지를 출력하게 구현했습니다
=> mod : password-chagne error message modify

src/api/user/index.ts, src/api/users/index.ts, src/components/mypage/PersonalInfo/personalImage.tsx, src/components/mypage/PersonalInfo/personalinfoBody.tsx, src/pages/PasswordChange/PasswordChangeLayout.tsx
유저 정보 수정 API를 PATCH로 하나로 묶었습니다.
users 와 user 디렉토리를 하나로 묶었습니다.
=> Mod: user info api change

src/components/productdetail/SellerButtons.tsx
글 삭제하면 main page로 redirect하게 만들었습니다.
=> fix: Redirect after delete

src/api/user/index.ts, src/pages/MyPage.tsx
=> feature sold-product

src/components/productdetail/ProductInfo.tsx
낙찰이 완료되었을 때 페이지가 다르게 보이게 했습니다.
=> feature: Change UI when product is sold

src/pages/mainpage.tsx
=> feature sold product doesn't show in mainpage

src/components/common/ItemList/ItemListBody/ItemButton.tsx, src/models/product.ts
=> mod : mainpage sold product
